### ISSUE TITLE
Make this a great CocoaPod

### ISSUE THREAD

**Issue by BenEmdon** [BenEmdon/CenteredCollectionView#1]
# Todo
- [x] Refactor code to be generically used
~~- [x] Turn into a framework ( #6 )~~
- [x] Example app using cocoapods
- [x] Make iOS deployment target 9.0 ( #7 )
- [ ] document code
- [x] Write readme
- [x] Write podspec description
- [x] Gifs
- [ ] Write unit tests
- [x] Publish cocoapod
